2分探索課題提出
algd2022/binary_search pull request #100
Opened 2022-06-27 06:16 UTC by Gatorasu

2022-07-02 08:27 UTC, nanashima requested changes
`spear.c` が正しくありません．

2022-07-02 08:27 UTC, nanashima commented on src/spear.c
> +	lb = -1;
最悪ゼロ割りします．初期値を見直しましょう．

2022-07-24 16:34 UTC, Gatorasu commented
初期値を変更しました。

2022-08-05 08:09 UTC, nanashima approved these changes

2022-08-05 08:09 UTC, closed without merging