演習-1-二分探索 提出
algd2022/binary_search pull request #104
Opened 2022-06-27 07:00 UTC by n2r2

2022-07-02 08:32 UTC, nanashima requested changes
`apple.c` `spear.c` `works.c` が正しく動いていません．

2022-07-02 08:32 UTC, nanashima commented on src/apple.c
> +    for (i = 1; i < n + 1; i++) {
`n=100000`のとき`i=n`で配列外参照します．他も同様です．

2022-07-02 09:50 UTC, n2r2 commented
3つのファイルを修正いたしました. よろしくお願い申し上げます.

2022-07-02 12:39 UTC, n2r2 commented on src/apple.c
> +    for (i = 1; i < n + 1; i++) {
3つのファイルを修正いたしました. よろしくお願い申し上げます.

2022-07-15 14:10 UTC, nanashima approved these changes

2022-07-15 14:10 UTC, closed without merging