提出
algd2022/binary_search pull request #107
Opened 2022-06-27 07:32 UTC by soyuva

受け取りよろしくお願いします

2022-07-02 08:41 UTC, nanashima requested changes
`apple.c` `spear.c` `works.c` が正しく動いていません．

2022-07-02 09:09 UTC, soyuva commented
お手数おかけしてすみません　これは問題文に与えられた以外の、特定の状況で動作しない(つまり初期値の問題)ということでしょうか

また、そもそも初期値に訂正を行ってよいのでしょうか　お答えいただけると幸いです

2022-07-02 10:30 UTC, nanashima reviewed
失礼しました．コメントが反映されていませんでした．
値が大きなケースで止まっていません．方針とかではなく単純にfor文の括弧の位置が変だと思います，

2022-07-02 13:13 UTC, soyuva commented
以下のfor文について括弧位置の訂正を行い、配列の繰り返し呼び出しを解消しました。
  for(i = 0; i < n; i++){
    scanf("%d", &A[i]);   
  }
なお、array.cには指摘がありませんでしたが、同様の問題があったため当方の判断で訂正しました。
お手数お掛けしてすみませんでした。再度、審査の方よろしくお願いします。

2022-07-25 11:21 UTC, nanashima approved these changes

2022-07-25 11:21 UTC, closed without merging