提出
algd2022/binary_search pull request #108
Opened 2022-06-27 07:50 UTC by toyama-keito

終わりました。

2022-07-02 08:43 UTC, nanashima requested changes
`array.c` `apple.c` `spear.c` `works.c` が正しく動いていません．
前半2つは逆だと思います．

2022-07-02 08:43 UTC, nanashima commented on src/spear.c
> +  ub = 1000000000;
初期値が不適切です．

2022-07-02 08:43 UTC, nanashima commented on src/works.c
> +int p(int l1,int l2,int l3, int X[]){
多くのケースで正しい値返していないので，もう一度確認してみてください．

2022-07-05 01:54 UTC, toyama-keito commented
前回の二分探索のプログラムを直したものを提出いたしました。
確認のほどよろしくお願いします。　　外山

2022-07-15 14:27 UTC, nanashima commented on src/array.c
> +  return X[i2] > i1;
条件違います．

2022-07-15 14:33 UTC, nanashima requested changes
変更分についてです
`array`: 正しい答えを返さないケースがあります．
`apple`: 初期値を改善出来ます．
 `works`: okです．

2022-07-15 14:33 UTC, nanashima commented on src/apple.c
> +  ub = 1000000001;
初期値が改善出来ます．

2022-07-15 14:33 UTC, nanashima commented on src/apple.c
> +  int sum = i1;
(これはただのコメントです)
結果的に式は同じになるのですが，個人的にどういう発想なのか気になりました．

2022-08-09 02:41 UTC, toyama-keito commented
改善しました。確認のほどよろしくお願いします。

2026-07-12 14:20 UTC, closed without merging