課題1二分探索
algd2022/binary_search pull request #111
Opened 2022-06-27 09:51 UTC by 1002sk

できました
なかなかに考えるのが難しかったです

2022-06-27 11:00 UTC, 1002sk commented
間違えを直しました

2022-07-02 08:46 UTC, nanashima requested changes
`array.c` `spear.c`  が正しくありません．

2022-07-02 08:46 UTC, nanashima commented on src/array.c
> +  int lb = 0;
初期値が不適切です．

2022-07-02 08:46 UTC, nanashima commented on src/spear.c
> +  ub = A[max];
初期値が不適切です．

2022-08-08 16:28 UTC, 1002sk commented
array.cとspear.cを修正しました。ご確認をお願いします。

2025-07-06 14:49 UTC, closed without merging