提出
algd2022/binary_search pull request #12
Opened 2022-06-19 03:14 UTC by KeisukeHoshiba

できたよー。

2022-07-01 13:34 UTC, nanashima requested changes
'apple.c' が正しくありません．また，初期値も改善できます(課題文を参照してください)

2022-07-01 13:34 UTC, nanashima commented on src/apple.c
> +    sum = sum + (A[j] + m + 1)/m;
資料のケースでも怪しいのでは？

2022-08-02 12:03 UTC, KeisukeHoshiba commented
再提出しましたので、採点よろしくお願い致します。

2022-08-05 07:37 UTC, nanashima approved these changes

2022-08-05 07:40 UTC, closed without merging