第2回課題提出
algd2022/binary_search pull request #121
Opened 2022-06-27 13:08 UTC by Sugi-kmmm

課題を提出します。
ご確認のほど、よろしくお願いいたします。

2022-07-02 08:57 UTC, nanashima requested changes
`spear.c` `works.c` が正しく動いていません．
また修正する場合は，答えだけ出力するようにしていただけると助かります．
（採点の都合ですが，大量のケースで動かすと出力がえらいことになるので．．．）

2022-07-02 08:57 UTC, nanashima commented on src/spear.c
> +      ub = A[i];
初期値が不適切です．

2022-07-02 08:57 UTC, nanashima commented on src/works.c
> +bool p(int x)
原因までは特定してませんが，多くのケースで正しく動いてないです．
もう一度確認してみてください．

2022-07-02 11:45 UTC, Sugi-kmmm commented on src/works.c
> +bool p(int x)
こちらの環境では正しく動いたいたのですが...
とりあえず了解いたしました
また、出力の方も了解です。

2022-07-02 13:54 UTC, nanashima commented on src/works.c
> +bool p(int x)
すぐに簡潔に書き表せるものとしては
`n=k=100000`
で'a_i'の値が全て'1'などですね．
後はでたらめなケースのほとんどでかなり大きめの値を出力しています．

2022-07-02 13:54 UTC, nanashima commented on src/works.c
> +bool p(int x)
修正期限は確認します

2022-07-02 15:17 UTC, nanashima commented on src/works.c
> +bool p(int x)
修正期限ですが，ちゃんとした日時は未定ですが，
例年では最終課題の締め切りと同じくらいです．
なので，他の課題も考慮しつつ計画的にやっていただければ大丈夫です．

2022-07-16 04:30 UTC, nanashima reviewed
`works`は依然いくつかのランダムケースで大きめの値を返しています．
`spear`はok(=基礎課題はok)です．

2022-07-16 04:30 UTC, nanashima commented on src/works.c
> +bool p(int x)
網羅は出来ていないかも知れませんが
気になったところをコメントします．

2022-07-16 04:30 UTC, nanashima commented on src/works.c
> +      if (temp < A[i] || i >= n)
ここを同時に処理しているのは怪しい気がします．
temp < A[I]のときは確かに良いのですが
i>=nの時も次の(外側のwhile)ループが続きcount足されてしまうので．
あとtemp<A[i]の条件式で配列外参照するのも怖いので，同じ式を書くなら
`i >= n || temp < A[i]` と書いた気が良いとも思います(i>=nのとき後半実行されない)

2022-08-06 14:17 UTC, Sugi-kmmm commented
ご指摘いただけた部分を修正しました
ご確認ください

2025-03-30 08:56 UTC, closed without merging