revised
algd2022/binary_search pull request #128
Opened 2022-06-27 14:43 UTC by nttitech

2022-07-02 09:02 UTC, nanashima requested changes
`works.c` が正しく動いていません．
また，`apple.c` の初期値が改善できます(課題文を参照してください)．

2022-07-02 09:02 UTC, nanashima commented on src/works.c
> +  ub = 100000;
初期値が不適切です．

2022-07-02 13:03 UTC, nttitech commented
修正しました

2022-07-16 04:38 UTC, nanashima approved these changes

2022-07-16 04:43 UTC, closed without merging