提出02
algd2022/binary_search pull request #138
Opened 2022-06-27 16:16 UTC by yutopanman

2022-07-02 09:17 UTC, nanashima requested changes
`spear.c` が正しくありません．
また，講義や資料の二分探索の(特にubとlbについての)解説を参考に `array.c`の余分な条件分岐を消してください．

2022-07-02 09:17 UTC, nanashima commented on src/spear.c
> +  ub = 1e9;
初期値が不適切です．

2022-07-02 09:17 UTC, nanashima commented on src/array.c
> +  if(p(A[ub]) == 0){
この条件分岐を無くしてください．

2022-07-03 14:45 UTC, yutopanman commented on src/spear.c
> +  ub = 1e9;
元のコードでは出力をlbとしているので答えが1e9のときに正しく出力できない。そこで初期値を
lb = 0, ub = 1e9+1
と修正しました。

2022-07-03 14:46 UTC, yutopanman commented on src/array.c
> +  if(p(A[ub]) == 0){
ub = n
と修正することで条件分岐を無くしました。

2022-07-03 14:47 UTC, yutopanman commented
課題のarray.cとspear.cのコードを修正しました。

2022-07-16 08:03 UTC, nanashima approved these changes

2022-07-16 08:03 UTC, closed without merging