提出
algd2022/binary_search pull request #14
Opened 2022-06-19 07:44 UTC by yukiyagi0

二分探索の課題の提出です。

2022-07-01 13:35 UTC, nanashima requested changes
'apple.c' 'works.c' の初期値が改善できます(課題文を参照してください)．

2022-07-01 14:12 UTC, yukiyagi0 commented
課題文のlb,ubの初期値はできるだけ良いものを選ぶというのは、講義中では入力制約で考えられる下限と上限の定数で良いと言われていました。

apple.c では制約は $1 <= n <= 10^5,1 <= a_i <= 10^9,n <= k <= 10^5$ です。
k= n,全ての$a_i=10^9$の時、求める答えは$10^9$でこれが上限です。
またk=n、全ての$a_i =1$の時、求める答えは1でこれが下限です。
講義中であったように二分探索は開区間でとったほうがよいとあったので$lb=0,ub=10^9+1$となり、改善の余地はないと思います。

works.cにおいても、制約は$1<=n<=10^5, 1<=a_i <= 10^4 , 1<=k <= n$であるので、
$n=10^5,k=1,全てのa_i=10^4$で求める答えは10^9でこれが上限です。
またk=n、全ての$a_i=1$の時、求める答えは1でこれが下限です。
講義中であったように二分探索は開区間でとったほうがよいとあったので$lb=0,ub=10^9+1$となり改善の余地はないと思います。

閉区間で取れば初期値が1改善できますが、講義ではこちらの書き方を薦められたので開区間で書いています。閉区間で取るべきということでしょうか？
それとも入力された配列を走査して、ub,lbを決めて改善せよ(例えばapple.cではmaxの要素をとるなど)ということですか？もしそうであるならば、講義では入力制約から考えられるギリギリの定数で良いとあったので、どちらに従うべきが教えていただきたいです。

2022-07-01 14:20 UTC, yukiyagi0 commented
講義で推奨されていたlb,ubの取り方は半開区間でした。開区間だと思っていたのは勘違いです。申し訳ございません。改善させていただきます。

2022-07-01 14:37 UTC, yukiyagi0 commented
apple.cとworks.cにおいて、ubを答えとしているのでub=1e9+1は取り得ない値であり、最適な初期値ではなかったので修正しました。

2022-07-12 14:54 UTC, nanashima approved these changes

2022-07-12 14:55 UTC, closed without merging