提出
algd2022/binary_search pull request #141
Opened 2022-06-27 17:19 UTC by merumerumerume

できました。

2022-07-02 09:25 UTC, nanashima requested changes
`spear.c` が正しくありません．
また，講義や資料の二分探索の(特にubとlbについての)解説を参考に `array.c` の余分な条件分岐を消してください．

2022-07-02 09:25 UTC, nanashima commented on src/spear.c
> +  ub = 1000000000;
初期値が不適切です．

2022-07-02 09:25 UTC, nanashima commented on src/array.c
> +  if(p(ub)){
これを消してください．

2022-07-02 16:50 UTC, merumerumerume commented on src/spear.c
> +  ub = 1000000000;
初期値を変更しました

2022-07-02 16:50 UTC, merumerumerume commented on src/array.c
> +  if(p(ub)){
消して、適切に動くように変更しました。

2022-07-02 16:55 UTC, merumerumerume reviewed
修正しました

2022-07-16 08:11 UTC, nanashima approved these changes

2022-07-16 08:14 UTC, closed without merging