提出
algd2022/binary_search pull request #143
Opened 2022-06-27 17:42 UTC by shu13579

提出

2022-07-02 09:27 UTC, nanashima requested changes
`spear.c` `works.c` が正しく動いていません．

2022-07-02 09:27 UTC, nanashima commented on src/spear.c
> +  ub = 1e9;
初期値が不適切です．

2022-07-02 09:27 UTC, nanashima commented on src/works.c
> +int p(int x){
原因は特定していませんが，例えば，
`2 2`
`1 1`
などで動いてないです．

2022-07-05 02:34 UTC, shu13579 commented
修正しました。

2022-07-16 08:11 UTC, nanashima approved these changes

2022-07-16 08:14 UTC, closed without merging