提出１
algd2022/binary_search pull request #146
Opened 2022-06-27 17:43 UTC by 21B13352

2022-06-27 23:59 UTC, 21B13352 commented
再提出

2022-07-02 09:36 UTC, nanashima requested changes
`array.c`  `works.c` が正しく動いていません．
また，`spear.c`の初期値が改善できます(課題文を参照してください)．

2022-07-02 09:36 UTC, nanashima commented on src/array.c
> +    if (A[ub - 1] <= k) {
正しくないです．
そもそもこの条件分岐は不要です(資料参考)．

2022-07-02 09:36 UTC, nanashima commented on src/works.c
>  int main(){
コンパイルエラーでてますよ．

2022-07-16 08:12 UTC, nanashima reviewed
全て正しく答えを返しています．
が`works`の初期値が改善出来ます(課題文参照)

2022-07-16 08:12 UTC, nanashima commented on src/works.c
> +    ub = 1000000001;
初期値を改善できます．

2022-07-25 15:48 UTC, 21B13352 commented
初期値を改善しました。

2022-08-05 08:14 UTC, nanashima approved these changes

2022-08-05 08:14 UTC, closed without merging