提出2
algd2022/binary_search pull request #159
Opened 2022-06-27 20:22 UTC by Tatsuuuya

よろしくお願いします。

2022-07-02 10:00 UTC, nanashima requested changes
`spear.c` が正しくありません．

2022-07-02 10:00 UTC, nanashima commented on src/spear.c
> +  lb = 100000001;
足りないです．
（あと細かい話ですがこれはもはや lb (lower bound)ではないのでは．．．）

2022-07-02 11:15 UTC, Tatsuuuya commented on src/spear.c
> +  lb = 100000001;
ご指摘ありがとうございます。訂正したものを提出しました。

2022-07-16 08:26 UTC, nanashima approved these changes

2022-07-16 08:26 UTC, closed without merging