提出　第2回
algd2022/binary_search pull request #163
Opened 2022-06-27 21:33 UTC by June-sixthmonth

2022-07-02 10:05 UTC, nanashima requested changes
`apple.c` `spear.c` `works.c` が正しく動いていません．もう一度確認してみてください．
あともし修正する場合は，答えだけ出力するようにしてください．
（採点の都合ですが，大量のケースで動かすと出力がえらいことになるので．）

2022-07-04 00:23 UTC, June-sixthmonth commented
修正しました。
確認をお願いいたします。

2022-07-16 09:11 UTC, nanashima requested changes
`spear`が境界値で正しい答えを返しません．
他はokです．

2022-07-16 09:11 UTC, nanashima commented on src/spear.c
> +        if (ub < A[i])ub = A[i];
初期値が不適切です．

2022-07-18 08:31 UTC, June-sixthmonth commented
再度修正しました。
よろしくお願いいたします。

2022-08-05 08:16 UTC, nanashima approved these changes

2022-08-05 08:16 UTC, closed without merging