提出
algd2022/binary_search pull request #17
Opened 2022-06-19 14:37 UTC by KimitakaIshiguro

2022-07-01 13:41 UTC, nanashima requested changes
'works.c' が正しくありません．

2022-07-01 13:41 UTC, nanashima commented on src/works.c
> +int p(int m){
例えば
`2 1`
`1 1`
とかで動いてないです．

2022-07-02 11:32 UTC, KimitakaIshiguro commented on src/works.c
> +int p(int m){
31行目の部分を修正しました。

2022-07-02 11:38 UTC, KimitakaIshiguro commented
'works.c'の31行目の部分を修正しました。

2022-07-12 14:55 UTC, nanashima approved these changes

2022-07-12 14:55 UTC, closed without merging