ver1
algd2022/binary_search pull request #170
Opened 2022-06-28 00:44 UTC by NW-Fallen

二回目の課題を提出させていただきます。ご確認ください。

2022-07-02 10:21 UTC, nanashima requested changes
`spear.c` が正しくありません．

2022-07-02 10:21 UTC, nanashima commented on src/spear.c
> +    if (A[i] > ub) ub = A[i];
初期値が不適切です．

2022-07-04 19:00 UTC, NW-Fallen commented
遅くなってしまいましたが、spear.cを初期値のみ修正し、更新させていただきました。

2022-07-16 09:27 UTC, nanashima approved these changes

2022-07-16 09:29 UTC, closed without merging