send
algd2022/binary_search pull request #174
Opened 2022-06-28 02:01 UTC by justinbiebertokyo

2022-07-02 10:53 UTC, nanashima requested changes
`spear.c` が正しく動いていません．

2022-07-02 10:53 UTC, nanashima commented on src/spear.c
> +ub = 1000000000 + 1；
全角になってます．コンパイルエラーでてますよ．

2022-07-02 10:53 UTC, nanashima commented on src/spear.c
> +  printf("%d\n", ub);
怪しいです．

2022-07-04 18:11 UTC, justinbiebertokyo commented
spear.cを訂正しました。よろしくお願いいたします。

2022-07-16 09:27 UTC, nanashima approved these changes

2022-07-16 09:29 UTC, closed without merging