提出
algd2022/binary_search pull request #176
Opened 2022-06-28 02:09 UTC by SuyasuyaNabi

2022-07-02 10:59 UTC, nanashima requested changes
`array.c` `apple.c`  が正しく動いていません．
また，講義や資料の二分探索の(特にubとlbについての)解説を参考に `array.c` `apple.c` `spear.c` `works.c`の余分な条件分岐を消してください．

2022-07-02 10:59 UTC, nanashima commented on src/apple.c
> -int main(){
資料のケースでも正しく動いてないのでは？
もう一度確認してみてください．

2022-07-02 10:59 UTC, nanashima commented on src/array.c
> +  int lb = 0, ub = n - 1;
初期値が不適切です．

2022-07-02 10:59 UTC, nanashima commented on src/array.c
> +  if (A[n - 1] < k)
この条件分岐を無くしてください

2022-07-02 10:59 UTC, nanashima commented on src/spear.c
> +  if (SumSpear(ub) < k)
`lb` `ub`を上手く設定して，この条件分岐を無くしてください．

2022-07-02 10:59 UTC, nanashima commented on src/works.c
> +  if (checkAllocWork(lb))
`lb` `ub`を上手く設定して，この条件分岐を無くしてください．

2022-07-02 10:59 UTC, nanashima commented on src/apple.c
> +  if (CountBagsNeed(lb) > k)
ここも無くしてください．

2022-07-06 01:00 UTC, SuyasuyaNabi commented
@nanashima 修正いたしました。よろしくお願いいたします。

2022-07-16 09:29 UTC, nanashima requested changes
spearが境界値で正しい答えを返しません．
他はokです．

2022-07-16 09:29 UTC, nanashima commented on src/spear.c
> +  int lb = 0, ub = 1e9;
`ub`の初期値が不適切です．

2022-08-30 11:22 UTC, closed without merging