課題提出
algd2022/binary_search pull request #183
Opened 2022-06-28 02:59 UTC by T-terrra

よろしくお願いいたします。

2022-07-02 11:11 UTC, nanashima requested changes
`spear.c` が正しくありません．

2022-07-02 11:11 UTC, nanashima commented on src/spear.c
> +  ub = 1e9;
初期値が不適切です．

2022-07-03 05:57 UTC, T-terrra commented
`spear.c`の`ub`を修正いたしました。
`spear.c`で初期値`ub=1e9`としてしまうと、槍の長さの最大値が`1e9`となる場合を除いてしまうことを考えられていませんでした。

2022-07-16 09:31 UTC, nanashima approved these changes

2022-07-16 09:31 UTC, closed without merging