submit
algd2022/binary_search pull request #27
Opened 2022-06-20 15:43 UTC by 20jun01

2022-07-01 14:01 UTC, nanashima requested changes
`array.c` `spear.c`  が正しくありません．
`apple.c` `works.c` の初期値が改善できます(課題文を参照してください)．

2022-07-01 14:01 UTC, nanashima commented on src/array.c
> +  lb = 0;
初期値が不適切です．

2022-07-01 14:01 UTC, nanashima commented on src/spear.c
> +  lb = 0 - 1e9;
初期値が不適切です．

2022-07-04 06:47 UTC, 20jun01 commented on src/array.c
> +  lb = 0;
修正しました

2022-07-04 06:48 UTC, 20jun01 commented on src/spear.c
> +  lb = 0 - 1e9;
修正しました

2022-07-12 14:58 UTC, nanashima approved these changes

2022-07-12 14:58 UTC, closed without merging