提出
algd2022/binary_search pull request #30
Opened 2022-06-21 07:18 UTC by Macky1x2

できたよお

2022-07-01 14:08 UTC, nanashima requested changes
正しく動いています．
講義や資料の二分探索の(特にubとlbについての)解説を参考に `array.c`の余分な条件分岐を消してください．

2022-07-01 14:08 UTC, nanashima commented on src/array.c
> +    if (A[n - 1] < k)ans = n;
これを消してください．

2022-07-03 19:19 UTC, Macky1x2 commented on src/array.c
> +    if (A[n - 1] < k)ans = n;
直しました。

2022-07-10 05:53 UTC, Macky1x2 commented
1週間前に変更したのですがご確認頂けましたか。

2022-07-10 06:50 UTC, nanashima commented
sortの方の次第が終わり次第，binary_searchの方の再提出もまとめて確認します．
もう少しお待ちください．

2022-07-11 09:00 UTC, Macky1x2 commented
わかりました。お忙しい中返信ありがとうございます。

2022-07-12 15:01 UTC, nanashima approved these changes

2022-07-12 15:05 UTC, nanashima reviewed
(上のapproved無視してください)
`array`が止まらなくなっていませんか？

2022-07-13 22:31 UTC, Macky1x2 commented
修正しました。ご確認お願いします。

2022-08-05 07:38 UTC, nanashima approved these changes

2022-08-05 07:40 UTC, closed without merging