submit 8.1-8.3
algd2022/binary_search pull request #38
Opened 2022-06-21 21:21 UTC by F1260

2022-07-01 14:29 UTC, nanashima requested changes
`array.c` が正しくありません．

2022-07-01 14:29 UTC, nanashima commented on src/array.c
> +  lb = 0;
初期値が不適切です．

2022-07-03 03:51 UTC, F1260 commented
array.cの初期値を訂正しました。

2022-07-12 15:16 UTC, nanashima approved these changes

2022-07-12 15:16 UTC, closed without merging