課題提出
algd2022/binary_search pull request #39
Opened 2022-06-22 06:14 UTC by katoro8989

2022-07-01 14:30 UTC, nanashima requested changes
`spear.c` が正しくありません．

2022-07-01 14:30 UTC, nanashima commented on src/spear.c
> +    ub = 1;
初期値が不適切です．

2022-07-04 03:01 UTC, katoro8989 commented on src/spear.c
> +    ub = 1;
変更しました

2022-07-04 03:01 UTC, katoro8989 commented
再提出

2022-07-12 15:19 UTC, nanashima approved these changes

2022-07-12 15:19 UTC, closed without merging