提出
algd2022/binary_search pull request #42
Opened 2022-06-22 14:56 UTC by sinc865

2022-07-01 14:33 UTC, nanashima requested changes
`array.c` が正しくありません．

2022-07-01 14:33 UTC, nanashima commented on src/array.c
> +    if(A[mid] > k)ub = mid;
条件式正しくないのでは．

2022-07-01 15:16 UTC, sinc865 commented on src/array.c
> +    if(A[mid] > k)ub = mid;
修正しましたので確認おねがいします.

2022-07-12 15:25 UTC, nanashima requested changes
`array`が値を正しく返さないケースがあります．
特に初期値を確認してください

2022-07-12 15:50 UTC, sinc865 commented
修正しました. お手数ですが確認おねがいします.

2022-07-12 16:02 UTC, nanashima approved these changes

2022-07-12 16:02 UTC, closed without merging