提出します
algd2022/binary_search pull request #46
Opened 2022-06-23 03:43 UTC by miyu-y

できるだけ簡潔にしました。

2022-07-01 14:39 UTC, nanashima requested changes
`apple.c` `spear.c` `works.c` が正しく動いていません．
おそらくどこかで配列外参照してます．

2022-07-01 14:39 UTC, nanashima commented on src/apple.c
> +    if(apple[mid]==1){
こういうところが怪しいような．．．

2022-07-01 23:55 UTC, miyu-y commented
while((ub-lb)>1)ということですか？
テストケースは正しく動いたのですが...

2022-07-12 15:30 UTC, nanashima requested changes
`array`以外が全て実行時エラーでてます．(おそらく配列外参照)
講義と資料を再度確認してください．

2022-07-12 15:30 UTC, nanashima commented on src/apple.c
> +    if(apple[mid]==1){
mid = 10^9/2 になったりするので
そのときapple[mid]で配列外参照するのではという意味です．

2022-07-12 16:18 UTC, miyu-y commented
配列に答えを保存しようとしたのがダメだったのですね...関数で計算するように修正しました。

2022-08-05 07:56 UTC, nanashima approved these changes

2022-08-05 07:57 UTC, closed without merging