提出
algd2022/binary_search pull request #47
Opened 2022-06-23 04:46 UTC by yzvvaaa

暑中お見舞申し上げます。

2022-07-01 14:43 UTC, nanashima requested changes
`spear.c` `works.c` が正しくありません．

2022-07-01 14:43 UTC, nanashima commented on src/spear.c
> +  ub = 1000000000;
初期値が不適切です．

2022-07-01 14:43 UTC, nanashima commented on src/works.c
> +  while(ub - lb > 1){
🤔

2022-07-01 14:44 UTC, nanashima commented on src/works.c
> +  ub = 10000;
初期値が不適切です．

2022-07-04 13:08 UTC, yzvvaaa commented on src/works.c
> +  ub = 10000;
0 < x <= 1000000000 のため、ubを1000000000に変更しました。

2022-07-04 13:12 UTC, yzvvaaa commented on src/spear.c
> +  ub = 1000000000;
0 <= x < 100000000000001 のためubを100000000000001に変更いたしました。

2022-07-12 15:34 UTC, nanashima requested changes
`works`はokです．
`spear`はそれだと`ub`桁あふれするのでもっと改善してください．

2022-08-08 18:23 UTC, yzvvaaa commented
ubを n * 1000000000 + 1 から 1000000000 + 1 に変更いたしました。

2026-04-02 15:50 UTC, closed without merging