submit
algd2022/binary_search pull request #48
Opened 2022-06-23 05:30 UTC by keito0tada

2022-07-01 14:44 UTC, nanashima requested changes
`spear.c` が正しくありません．

2022-07-01 14:44 UTC, nanashima commented on src/spear.c
> +    ub = 1000000000 - 1;
初期値が不適切です．

2022-07-05 04:27 UTC, keito0tada commented on src/spear.c
> +    ub = 1000000000 - 1;
ub=10^9に修正しました。よろしくお願いいたします。

2022-07-12 15:37 UTC, nanashima requested changes
`ub=10^9`だとまだ槍を作れる可能性があります．
長さ10^9の木から長さ10^9の槍は作れるので．

2022-07-18 18:48 UTC, keito0tada commented
ub=10^9+1に修正しました。
最大値xがlb<=x<ubに存在するとしているため、xが10^9になる可能性がある以上はubは10^9より大きくなくてはならないという理解で正しいでしょうか。

2022-08-05 07:57 UTC, nanashima approved these changes
その理解で正しいです．
演習お疲れ様でした．

2022-08-05 07:57 UTC, closed without merging