第2回提出
algd2022/binary_search pull request #51
Opened 2022-06-23 10:57 UTC by taiki-sato

仕事の分配はやり方がわからなかった

2022-07-01 14:50 UTC, nanashima requested changes
`spear.c` が正しくありません．

2022-07-01 14:50 UTC, nanashima commented on src/spear.c
> +  ub = 1000000000;
初期値が不適切です．

2022-07-09 07:37 UTC, taiki-sato commented on src/spear.c
> +  ub = 1000000001;
ub = 1000000000　だと槍が作れる場合があることを見逃していた

2022-07-09 07:38 UTC, taiki-sato commented
ub=1000000000だと槍を作れる場合があることを見逃していた。

2022-07-15 03:30 UTC, nanashima approved these changes

2022-07-15 03:30 UTC, closed without merging