Submit.
algd2022/binary_search pull request #56
Opened 2022-06-24 01:36 UTC by yodai49

二部探索の部分は出来る限り4つの課題の間で使い回せるように、評価部分をモジュール化したのが工夫点である。

2022-07-01 14:54 UTC, nanashima requested changes
`spear.c` が正しくありません．

2022-07-01 14:54 UTC, nanashima commented on src/spear.c
> +  int max=1000000000;//10^9
初期値が不適切です．

2022-07-06 11:15 UTC, yodai49 commented
ご指摘ありがとうございます。修正しました。

2022-07-15 03:31 UTC, nanashima approved these changes

2022-07-15 03:33 UTC, closed without merging