提出
algd2022/binary_search pull request #61
Opened 2022-06-24 13:51 UTC by SSlime-s

2022-07-01 15:07 UTC, nanashima requested changes
正しく動いています．
講義や資料の二分探索の(特にubとlbについての)解説を参考に `array.c` `apple.c` `spear.c` の余分な条件分岐を消してください．

2022-07-01 15:07 UTC, nanashima commented on src/array.c
> +  if (A[n - 1] < k) {
この条件分岐をなくしてください．

2022-07-01 15:07 UTC, nanashima commented on src/array.c
> +  if (A[0] >= k) {
ここもです．

2022-07-01 15:07 UTC, nanashima commented on src/spear.c
> +  if (!check(lb)) {
ここもです．

2022-07-01 15:07 UTC, nanashima commented on src/apple.c
> +  if (check(lb)) {
ここもです．

2022-07-04 14:32 UTC, SSlime-s commented on src/array.c
> +  if (A[n - 1] < k) {
ここ含め事前に条件分岐をしなくていいように変更しました :bow:

2022-07-15 03:37 UTC, nanashima approved these changes

2022-07-15 03:38 UTC, closed without merging