revised
algd2022/binary_search pull request #65
Opened 2022-06-24 23:55 UTC by takuya-13068

2022-07-01 15:15 UTC, nanashima requested changes
`spear.c` が正しくありません．

2022-07-01 15:15 UTC, nanashima commented on src/spear.c
> +  ub = max1(k, A);
初期値が不適切です．

2022-07-04 02:43 UTC, takuya-13068 commented
初期値のubを修正しました。どうでしょうか。

2022-07-15 03:37 UTC, nanashima approved these changes

2022-07-15 03:38 UTC, closed without merging