提出
algd2022/binary_search pull request #70
Opened 2022-06-25 07:49 UTC by kkklp

よろしくお願いいたします．

2022-07-01 15:22 UTC, nanashima requested changes
正しく動いていますが，`apple.c`の初期値が改善できます(課題文を参照してください)．
また，資料の二分探索の(特にubとlbについての)解説を参考に `array.c`の余分な条件分岐を消してください．

2022-07-01 15:22 UTC, nanashima commented on src/array.c
> +  if (A[0] >= k) {
この条件分岐をなくしてください．

2022-07-01 15:22 UTC, nanashima commented on src/array.c
> +  if (A[n - 1] < k) {
これもです．

2022-07-03 19:20 UTC, kkklp commented
ご指摘いただきありがとうございます．変更した点は
- `apple.c`の初期値
- `array.c`の余分な条件分岐の削除
の2つです．よろしくお願い致します．

2022-07-15 03:41 UTC, nanashima approved these changes

2022-07-15 03:41 UTC, closed without merging