提出
algd2022/binary_search pull request #74
Opened 2022-06-25 20:09 UTC by KojimaIssei

あ

2022-07-01 15:42 UTC, nanashima requested changes
`array.c`  が正しくありません．
また，`apple.c` `spear.c` `works.c`の計算量を改善してください．

2022-07-01 15:42 UTC, nanashima commented on src/array.c
> +  lb=0;
初期値が不適切です．

2022-07-01 15:42 UTC, nanashima commented on src/apple.c
> +    B[x]=p(x);
ここの不要な計算で`O(n^2)`かかり，二分探索の意味がなくなってしまいます．
他も同様です．

2022-07-02 13:34 UTC, KojimaIssei commented
修正しました。

2022-07-15 03:42 UTC, nanashima requested changes
`spear`が正しくありません．
他は合ってます．

2022-07-15 03:42 UTC, nanashima commented on src/spear.c
> +  ub = 1000000000;
初期値が不適切です．

2022-07-25 16:53 UTC, KojimaIssei commented
spear.cを修正しました。

2022-08-05 08:04 UTC, nanashima approved these changes

2022-08-05 08:04 UTC, closed without merging