提出
algd2022/binary_search pull request #8
Opened 2022-06-18 01:26 UTC by 1noino

2022-07-01 13:15 UTC, nanashima requested changes
'works.c' が正しくないです．

2022-07-01 13:15 UTC, nanashima commented on src/works.c
> +  ub = 100000000; // ok (10**9)
惜しいです．`1e9`と書くのもありです．

2022-07-01 21:27 UTC, 1noino commented on src/works.c
> +  ub = 100000000; // ok (10**9)
指摘をありがとうございます。
ubについて、100000000(1e8)となっていたものを1e9に修正しました。

2022-07-01 21:29 UTC, 1noino commented on src/works.c
> +  ub = 100000000; // ok (10**9)
一時的に新しいPCに差し替えている(修理中)ため、user名がおかしくなってしまいましたが修正したのは私です。
また、最後に間違ってcommitしたexeファイルは無視してください。こちらで削除しようとしましたが、削除できませんでした。申し訳ありません。

2022-07-12 14:54 UTC, nanashima approved these changes

2022-07-12 14:55 UTC, closed without merging