提出
algd2022/binary_search pull request #81
Opened 2022-06-26 10:33 UTC by Ryoya-Yoshimura

2022-07-02 07:55 UTC, nanashima requested changes
`spear.c` が正しくありません．
また，`spear.c` `apple.c` `works.c` の初期値が改善できます(課題文を参照してください)．

2022-07-02 07:55 UTC, nanashima commented on src/spear.c
> +  ub = n*1000000000+1;
初期値が大きすぎて最悪桁あふれします．

2022-07-02 13:10 UTC, Ryoya-Yoshimura commented on src/spear.c
> +  ub = n*1000000000+1;
修正いたしました。ご指摘ありがとうございます。

2022-07-15 04:02 UTC, nanashima approved these changes

2022-07-15 04:02 UTC, closed without merging