提出
algd2022/binary_search pull request #82
Opened 2022-06-26 10:39 UTC by K-Kumamoto

2022-07-02 07:57 UTC, nanashima requested changes
`apple.c` `spear.c` が正しくありません．

2022-07-02 07:57 UTC, nanashima commented on src/apple.c
> +  for(i= 1; i <= n; i++){
ここ怪しいです．

2022-07-02 07:57 UTC, nanashima commented on src/spear.c
> +  for(i = 1; i < n; i++){
ここもです．

2022-07-02 16:37 UTC, K-Kumamoto commented
修正しました

2022-07-15 04:04 UTC, nanashima commented on src/apple.c
> +  for(i= 0; i <= n; i++){
ここ'n'までループすると'n=100000'の時配列外参照します．

2022-07-15 04:04 UTC, nanashima requested changes
`apple`で配列外参照します．
他の課題はokです．

2022-07-21 03:55 UTC, K-Kumamoto commented
修正しました

2022-08-05 08:09 UTC, nanashima approved these changes

2022-08-05 08:09 UTC, closed without merging