提出
algd2022/binary_search pull request #88
Opened 2022-06-26 15:28 UTC by Guppi12172

2022-07-02 08:05 UTC, nanashima requested changes
`apple.c` `spear.c`が正しく動いていません．

2022-07-02 08:05 UTC, nanashima commented on src/apple.c
> +  ub = 1000000001;
資料のケースは正しく動いていますか？
初期値だったり二分探索部だったりが怪しいです．

2022-07-02 08:05 UTC, nanashima commented on src/spear.c
> +  ub = 1000000001;
初期値が不適切です．

2022-07-02 11:40 UTC, Guppi12172 commented
修正しました。反映されているでしょうか？

2022-07-02 14:05 UTC, nanashima commented
はい．反映されています．

2022-07-15 10:22 UTC, nanashima approved these changes

2022-07-15 10:22 UTC, closed without merging