提出
algd2022/binary_search pull request #9
Opened 2022-06-18 06:16 UTC by Hydra966

if(){}
else if(){}
else{}
と
if(){}
else{
    if(){}
    else{}
}
の間に違いはあるのでしょうか

2022-07-01 13:17 UTC, nanashima commented on src/works.c
> +int A[10000];
足りません．

2022-07-01 13:17 UTC, nanashima requested changes
'works.c' が正しくありません．
あと 'apple.c' 'works.c' の初期値が改善できます(課題文を参照してください)．

2022-07-02 00:06 UTC, Hydra966 commented
ご指摘ありがとうございます。
apple.c および works.c のubを修正しました。
また works.c における配列Aの最大サイズを修正しました。（nの最大値ではなくa_iの最大値を適用してしまっていました）
加えて、works.c の関数 p においてAの要素が引数より大きかった時の処理を簡潔な形に変更し、また k_allo (仕事が割り当てられた人数)のカウントの仕方を簡潔な形に変更しました。

2022-07-12 14:54 UTC, nanashima approved these changes

2022-07-12 14:55 UTC, closed without merging