提出
algd2022/binary_search pull request #91
Opened 2022-06-26 16:09 UTC by grkon03

プロトタイプ宣言してmainの下に関数書いた方が見やすいですかね...？
ちょっと見づらいもので申し訳ないです

2022-07-02 08:13 UTC, nanashima requested changes
`array.c` `apple.c` `spear.c` が正しく動いていません．

2022-07-02 08:13 UTC, nanashima commented on src/array.c
> +  lb = 0;
初期値が不適切です．

2022-07-02 08:13 UTC, nanashima commented on src/apple.c
> +  return n * max_p;
最悪桁あふれします．
初期値を改善しましょう．

2022-07-02 08:13 UTC, nanashima commented on src/spear.c
> +  ub = sup_about();
初期値が不適切です．

2022-07-04 13:08 UTC, grkon03 commented
これでどうでしょうか？

2022-07-15 10:27 UTC, nanashima requested changes
`spear`がいくつかのケース(資料のサンプル2など)で正しい答えを返してないです．
他はokです．

2022-07-15 10:27 UTC, nanashima commented on src/spear.c
> +  return (k < sum);
k=sumのケースも条件を満たすのでは？

2022-07-19 07:09 UTC, grkon03 commented
修正しました
よろしくお願いします

2022-08-05 08:09 UTC, nanashima approved these changes

2022-08-05 08:09 UTC, closed without merging