提出
algd2022/binary_search pull request #93
Opened 2022-06-26 16:45 UTC by KITAMURATomohiro

2022-07-02 08:14 UTC, nanashima requested changes
`spear.c` が正しくありません．

2022-07-02 08:14 UTC, nanashima commented on src/spear.c
> +  ub = 1e9;
初期値が不適切です．

2022-07-02 10:28 UTC, KITAMURATomohiro commented on src/spear.c
> +  ub = 1e9;
修正しましたので再提出いたします

2022-07-15 10:39 UTC, nanashima approved these changes

2022-07-15 14:06 UTC, closed without merging