提出
algd2022/binary_search pull request #96
Opened 2022-06-27 01:49 UTC by surumesiokoji

仕事量の問題が難しかったです。

2022-07-02 08:24 UTC, nanashima reviewed
`works.c` が正しく動いていません．他は合ってます．

2022-07-02 08:24 UTC, nanashima commented on src/works.c
>    }
??

2022-07-02 10:58 UTC, surumesiokoji commented on src/works.c
>    }
提出する前に間違えてctrl+zを押してしまったのか誤った状態で提出してしまいました。申し訳ありません。
while文中のスペース2つを加え、45行目のreturn0とprintfの間の { をprintfの直前に移動させました。反映されているか自信がないのですがこれで問題ないでしょうか。

2022-07-15 10:42 UTC, nanashima requested changes
まだ`works`が正しく動かない(止まらない)ケースがあります．
`for`文の括弧の位置が変です．

2022-07-15 12:52 UTC, surumesiokoji commented
修正しました。

2022-08-05 08:09 UTC, nanashima approved these changes

2022-08-05 08:09 UTC, closed without merging